version: "3.7"
services:
    db:
        image: postgres
        ports:
        - 5432:5432
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: wallet-api

